sources:
  - name: sf-protocol
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/30564/sf-protocol-dev-arb-sepolia/0.0.4
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - ../../queries/development/*.{ts,tsx,js,jsx}
  - ../../queries/development/*.graphql
