sources:
  - name: secured-finance-protocol
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/secured-finance/secured-finance-protocol
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - './src/queries/*.{ts,tsx,js,jsx}'
  - './src/queries/*.graphql'
