sources:
  - name: sf-protocol
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/secured-finance/{env.SUBGRAPH_NAME}
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - '../../queries/*.{ts,tsx,js,jsx}'
  - '../../queries/*.graphql'
