sources:
  - name: sf-protocol
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/64582/sf-prd-avalanche-mainnet/0.1.0
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - ../../queries/production/*.{ts,tsx,js,jsx}
  - ../../queries/production/*.graphql
