sources:
  - name: sf-protocol
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/30564/sf-protocol-stg-ava-fuji/0.0.1
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - ../../queries/development/*.{ts,tsx,js,jsx}
  - ../../queries/development/*.graphql
