name: Validate Pull Request
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks-pr:
    name: Validate Pull Request
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Lint Code
        run: npm run lint:check
      - name: Format Code
        run: npm run format
      - name: Generate artifacts
        run: npm run codegen
      - name: Build Repo
        run: npm run build
      - name: Execute Test
        run: npm run test-all
      - name: Execute Coverage
        run: npm run coverage
      - name: Upload app coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./packages/chainlink-external-adapter/coverage/coverage-final.json
          flags: chainlink-external-adapter
          token: ${{ secrets.CODECOV_TOKEN }}
