name: Deploy Graph

on:
  push:
    branches:
      - main
      - development
      - SF-139-only-subgraph

jobs:
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Deploy Subgraph
        id: deploy
        run: |
          cd ./packages/secured-finance-subgraph
          yarn global add @graphprotocol/graph-cli
          echo "$(yarn global bin)" >> $GITHUB_PATH
          graph deploy --access-token ${{secrets.GRAPH_ACCESS_TOKEN}} secured-finance/secured-finance-protocol subgraph.yaml --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/
        shell: bash
