name: Deploy Graph

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'packages/secured-finance-subgraph/**'

jobs:
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Install Graph CLI
        id: install-graph-cli
        run: |
          yarn global add @graphprotocol/graph-cli@0.28.0
          echo "$(yarn global bin)" >> $GITHUB_PATH
        shell: bash
      - name: Deploy Subgraph
        id: deploy
        run: |
          cd ./packages/secured-finance-subgraph
          graph deploy --access-token ${{secrets.GRAPH_ACCESS_TOKEN}} secured-finance/secured-finance-protocol subgraph.yaml --ipfs https://api.thegraph.com/ipfs/ --node https://api.thegraph.com/deploy/
        shell: bash
