name: Deploy and Publish

on:
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'True to bypass the check for changes'
        required: false
        type: boolean
  push:
    branches:
      - main
      - develop

jobs:
  paths:
    name: Path Filter
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'secured-finance-machine-user[bot]' }}
    outputs:
      subgraph: ${{ steps.changes.outputs.subgraph }}
    steps:
      - uses: actions/checkout@v3
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Check Paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          base: ${{ steps.extract_branch.outputs.branch }}
          filters: |
            subgraph:
              - 'packages/secured-finance-subgraph/src/**'
              - 'packages/secured-finance-subgraph/schema.graphql'
              - 'packages/secured-finance-subgraph/subgraph.yaml'
              - 'packages/secured-finance-subgraph/package.json'
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    needs: [paths]
    if: ${{ needs.paths.outputs.subgraph == 'true' || github.event.inputs.force_publish == 'true' }}
    steps:
      - run: echo "${{ needs.paths.outputs.subgraph }}"
      - run: echo "${{ needs.paths.outputs.client }}"
      - run: echo "${{ needs.paths.outputs.packages }}"
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy Subgraph
        id: deploy
        run: |
          cd ./packages/secured-finance-subgraph
          npm run auth ${{secrets.GRAPH_ACCESS_TOKEN}}
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npm run update-subgraphrc staging
            version=$(cat deployment.json | jq -r .staging.version | tr -d '"')
            npm run generate:stg
            npm run deploy:stg ${version}
          else
            npm run update-subgraphrc development
            version=$(cat deployment.json | jq -r .development.version | tr -d '"')
            npm run generate:dev
            npm run deploy:dev ${version}
          fi
      - name: Commit and push
        shell: bash
        run: |
          npm run format:fix
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update .subgraphrc"
          git push
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: [deploy, paths]
    if: ${{ always() && github.actor != 'secured-finance-machine-user[bot]' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repository
        run: npm run bootstrap
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set env for development environment
        if: ${{ steps.extract_branch.outputs.branch == 'develop' }}
        run: |
          echo "NETWORK=development" >> $GITHUB_ENV
      - name: Set env for staging environment
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        run: |
          echo "NETWORK=staging" >> $GITHUB_ENV
      - name: Get subgraph version
        run: |
          version=$(cat ./packages/secured-finance-subgraph/deployment.json | jq -r .$NETWORK.version | tr -d '"')
          echo "::set-output name=version::${version}"
        id: subgraph_version
      - name: Update subgraph version
        run: npx nx run @secured-finance/sf-graph-client:update-subgraph-version --environment $NETWORK --label ${{ steps.subgraph_version.outputs.version}}
      - name: Check diff
        shell: bash
        id: diff
        run: |
          npm run format:fix
          echo "::set-output name=count::$(git diff --name-only . | wc -l)"
      - name: Commit
        shell: bash
        if: steps.diff.outputs.count > 0
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update .graphclientrc.yml"
      - name: Generate artifacts
        run: npm run codegen
      - name: Version and Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npx lerna version --conventional-commits --conventional-graduate --yes
          else
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          fi
          npx lerna publish from-package --conventional-commits --yes
