name: Deploy Graph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      # For testing
      - SF-180-update-subgraph
    # paths:
    #   - 'packages/secured-finance-subgraph/**'

jobs:
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    if: github.actor != 'secured-finance-machine-user[bot]'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Change directory
        run: cd ./packages/secured-finance-subgraph
      - name: Update .subgraphrc for development environment
        # For testing
        # if: ${{ steps.extract_branch.outputs.branch == 'develop' }}
        if: ${{ steps.extract_branch.outputs.branch == 'SF-180-update-subgraph' }}
        run: |
          version=$(npm run update-subgraphrc development)
          echo "::set-output name=npm-version::${version}"
      - name: Update .subgraphrc for staging environment
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        run: |
          version=$(npm run update-subgraphrc staging)
          echo "::set-output name=npm-version::${version}"
      - name: Deploy Subgraph
        id: deploy
        run: |
          npm run auth ${{secrets.GRAPH_ACCESS_TOKEN}}
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npm run generate:stg
            npm run deploy:stg v${{ steps.package-version.outputs.npm-version}}
          else
            npm run generate:dev
            npm run deploy:dev v${{ steps.package-version.outputs.npm-version}}
          fi
      - name: Commit and push
        shell: bash
        run: |
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git commit -m "chore: update .subgraphrc"
          git push
