name: Deploy Graph

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      # For testing
      - SF-180-update-subgraph

jobs:
  filter:
    name: Path Filter
    runs-on: ubuntu-latest
    if: github.actor != 'secured-finance-machine-user[bot]'
    outputs:
      subgraph: ${{ steps.filter.outputs.subgraph }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            subgraph:
              - 'packages/secured-finance-subgraph/**'
  deploy:
    name: Deploy Graph
    runs-on: ubuntu-latest
    needs: [filter]
    if: needs.filter.outputs.subgraph == 'true'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repo
        run: npm run bootstrap
      - name: Build
        run: npm run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Deploy Subgraph
        id: deploy
        run: |
          cd ./packages/secured-finance-subgraph
          npm run auth ${{secrets.GRAPH_ACCESS_TOKEN}}
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npm run update-subgraphrc staging
            version=$(cat deployment.json | jq -r .staging.version | tr -d '"')
            npm run generate:stg
            npm run deploy:stg ${version}
          else
            npm run update-subgraphrc development
            version=$(cat deployment.json | jq -r .development.version | tr -d '"')
            npm run generate:dev
            npm run deploy:dev ${version}
          fi
      - name: Commit and push
        shell: bash
        run: |
          npm run format:fix
          git config user.name "SF Machine User[bot]"
          git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update .subgraphrc"
          git push
