name: Publish to NPM

on:
  push:
    branches:
      - main
      - develop

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Bootstrap Repository
        run: npm run bootstrap
      - name: Generate artifacts
        run: npm run codegen
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: "Setup npm"
        run: |
          npm set @secured-finance:registry=https://npm.pkg.github.com
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"
      - name: Version and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          if [ ${{ steps.extract_branch.outputs.branch }} = main ]; then
            npx lerna version --conventional-commits --conventional-graduate --yes
          else
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes --force-publish
          fi
          npx lerna publish from-package --conventional-commits --yes
