name: Publish GitBook

on:
  push:
    branches:
      - SF-1009 

jobs:
  publish-gitbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install GitBook CLI
        run: npm install -g gitbook-cli

      - name: Build GitBook
        run: |
          gitbook init
          mv packages/sf-client/docs/* .
          gitbook build

      - name: Deploy GitBook to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _book
