name: Publish to NPM

on:
  push:
    branches:
      - SF-71-automate-publish
  pull_request:
    types: [closed]
    branches:
      - main
      - development

jobs:
  publish-npm:
    #if: github.event.pull_request.merged == true
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install Dependencies
        run: npm install
      - name: Bootstrap Repository
        run: npm run bootstrap
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Version and Publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          if [ "${{ steps.extract_branch.outputs.branch }}" != "main" ]; then
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          else
            npx lerna version --conventional-commits --conventional-graduate --yes
          fi
          npx lerna publish --conventional-commits --yes
