name: Documentation Generation

on:
  push:
    branches:
      - SF-1009 

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    if: ${{ always() && github.actor != 'secured-finance-machine-user[bot]' && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.MACHINE_USER_APP_ID }}
          private_key: ${{ secrets.MACHINE_USER_PRIVATE_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Set env
        run: |
          echo "NPM_AUTH_TOKEN=${{ secrets.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm ci

      - name: Bootstrap Repository
        run: npm run bootstrap

      - name: Generate artifacts
        run: npm run codegen

      - name: Generate Documentation
        run: npm run docs

      - name: Check Diff
        id: docsDiff
        run: echo "count=$(git diff --staged --name-only . | wc -l)" >> ${{ github. workspace }}/output.txt

      - name: Commit and Push
        if: steps.docsDiff.outputs.count > 0
        run: |
              git config user.name "SF Machine User[bot]"
              git config user.email "${{ secrets.MACHINE_USER_APP_ID }}+sf-machine-user[bot]@users.noreply.github.com"
              git commit -am "chore: update docs" --no-verify
              git push