name: Publish to NPM

on:
  push:
    branches:
      - main
      - development

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Install Dependencies
        run: yarn install
      - name: Bootstrap Repository
        run: yarn run bootstrap
      - name: Build packages
        run: yarn run build
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Version and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          if [ "${{ steps.extract_branch.outputs.branch }}" = "main" ]; then
            npx lerna version --conventional-commits --conventional-graduate --yes
          else
            npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
          fi
          npx lerna publish from-git --conventional-commits --yes
