sources:
  - name: sf-protocol
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/1749811/sf-prd-arbitrum-one/0.1.2
    transforms:
      - blockTracking:
          validateSchema: true
      - autoPagination:
          validateSchema: true
documents:
  - ../../queries/production/*.{ts,tsx,js,jsx}
  - ../../queries/production/*.graphql
